services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: center_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - center
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: center_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: center
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: center
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - center
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: center_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - center
    depends_on:
      - app

networks:
  center:
    driver: bridge

volumes:
  dbdata:
    driver: local
